# Generated by Django 2.2 on 2019-08-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_latitude', models.FloatField()),
                ('loc_longitude', models.FloatField()),
                ('seeker_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
